version: "3.4"
services:
  edsl_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID}"
        GID: "${GID}"
        USER: "${USER}"
    image: "${USER}/edsl"
    ipc: "host"
    cap_add:
      - SYS_PTRACE
    network_mode: "host"
    security_opt:
      - "seccomp=unconfined"
    volumes:
      - "${HOME}:${HOME}"
      - "local-files:/var/${USER}"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/etc/apt:/etc/apt"

volumes:
  local-files:
